name: Packer Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build-packer-image:
    name: Package format & Validate
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Build the HealthCheck JAR file
        run: |
          # cd ./HealthCheck  # Navigate to the directory containing your Spring Boot app
          mvn clean -B package  # Build the JAR file (ensure your pom.xml is correctly configured)
        


      - name: Install Packer
        uses: hashicorp/setup-packer@main

      # - name: Install Packer Google Cloud Plugin
      #   run: cd ../packer && packer plugins install github.com/hashicorp/googlecompute

      - name: Initialize Packer
        working-directory: ./packer
        run: packer init .

      - name: Run Packer fmt Check
        working-directory: ./packer
        run: |
          packer fmt -check -diff .
        continue-on-error: false

      - name: Run Packer Validate
        working-directory: ./packer
        run: packer validate -var "DB_URL=${{ secrets.DB_URL }}" \
                          -var "DB_USRNAME=${{ secrets.DB_USRNAME }}" \
                          -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
                          -var "DB_NAME=${{ secrets.DB_NAME }}" \
                          -var "subnet_id=${{ secrets.subnet_id }}" \
                          -var "instance_type=${{ secrets.instance_type }}" \
                          -var "PRT_NBR=${{ secrets.PRT_NBR }}" \
                          -var "gcp_project_id=${{ secrets.gcp_project_id }}" \
                          packer.pkr.hcl