name: Packer CI - Format & Validate

on:
  pull_request:
    branches:
      - main  # Trigger the workflow only for PRs targeting the 'main' branch

jobs:
  packer-checks:
    runs-on: ubuntu-latest  # Use an Ubuntu environment for the CI workflow

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out the latest code from the repository

      # Step 2: Install Packer
      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -  # Add Packer GPG key
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"  # Add Packer repository
          sudo apt update && sudo apt install -y packer  # Install Packer

      # Step 3: Initialize the Packer template
      - name: Initialize Packer Template
        run: |
          packer init packer.pkr.hcl
        working-directory: packer
      # Step 3: Run packer fmt to check formatting
      - name: Run Packer Format Check
        run: |
          packer fmt -check .  # Checks if the Packer template is correctly formatted. If modified, it fails
        working-directory: packer  # Navigate to the 'packer' directory before running the command

      # Step 4: Run packer validate to validate the Packer template
      - name: Run Packer Validate
        run: |
          packer validate \
            -var "DB_URL=${{ secrets.DB_URL }}" \
            -var "DB_USRNAME=${{ secrets.DB_USRNAME }}" \
            -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            -var "DB_NAME=${{ secrets.DB_NAME }}" \
            -var "subnet_id=${{ secrets.subnet_id }}" \
            -var "instance_type=${{ secrets.instance_type }}" \
            -var "PRT_NBR=${{ secrets.PRT_NBR }}" \
            -var "gcp_project_id=${{ secrets.gcp_project_id }}" \
            packer.pkr.hcl    # Validates the Packer template. If it fails, the workflow fails
        working-directory: packer  # Navigate to the 'packer' directory before running the command