name: Packer Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test-development:
    name: Run Application Tests and Validate Packer
    runs-on: ubuntu-latest
    environment: development

    env:
      # Application Variables
      DB_URL: ${{ secrets.DB_URL }}
      DB_USRNAME: ${{ secrets.DB_USRNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # Packer Variables (Automatically Picked Up)
      PKR_VAR_DB_URL: ${{ secrets.DB_URL }}
      PKR_VAR_PRT_NBR: ${{ secrets.PRT_NBR }}
      PKR_VAR_DB_USRNAME: ${{ secrets.DB_USRNAME }}
      PKR_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PKR_VAR_DB_NAME: ${{ secrets.DB_DATABASE }}
      PKR_VAR_SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      PKR_VAR_SUBNET_ID: ${{ secrets.SUBNET_ID }}
      PKR_VAR_INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
      PKR_VAR_REGION: ${{ secrets.REGION }}

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Build the HealthCheck JAR file and Set Up Dependencies and Run Tests
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          PORT: ${{ secrets.PORT }}
        run: |
          cd HealthCheck  # Navigate to the directory containing your Spring Boot application
          mvn clean -B package  # Build the JAR file (ensure your pom.xml is correctly configured)
        


      - name: Install Packer
        uses: hashicorp/setup-packer@main

      # - name: Install Packer Google Cloud Plugin
      #   run: cd ../packer && packer plugins install github.com/hashicorp/googlecompute

      - name: Initialize Packer
        working-directory: packer
        run: packer init .

      - name: Run Packer fmt Check
        working-directory: packer
        run: |
          packer fmt -check -diff .
        continue-on-error: false

      - name: Run Packer Validate (AWS)
        working-directory: packer
        run: |
          packer validate -var-file="variables.pkrvars.hcl" -var "REGION=us-east-1" aws_ami.pkr.hcl

      - name: Run Packer Validate (GCP)
        working-directory: packer
        run: |
          packer validate -var-file="variables.pkrvars.hcl" -var "REGION=us-east-1" gcp_image.pkr.hcl  
